/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.RegistredUser;
import domain.Role;
import java.awt.Toolkit;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import utilities.PropertiesController;

/**
 *
 * @author erome
 */
public class AdminRolesGUI extends javax.swing.JFrame {

    /**
     * Creates new form UserAdminGUI
     */
    public AdminRolesGUI() {
        initComponents();
        setProgramIcon();
    }
    
    private void setProgramIcon(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("resources/client_icon_32.png")));
    }
    
    private JFrame parent;
    private RegistredUser myUser;
    public AdminRolesGUI(JFrame parent, RegistredUser myUser) {
        this();
        this.parent = parent;
        this.myUser = myUser;
        
        this.parent.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        lblAdminProfiles = new RSMaterialComponent.RSLabelTextIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new RSMaterialComponent.RSTableMetroCustom();
        btnClose = new RSMaterialComponent.RSButtonIconOne();
        btnUpdateList = new RSMaterialComponent.RSButtonIconOne();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRoles = new RSMaterialComponent.RSTableMetroCustom();
        btnCreateRole = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnAsignRole = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnRoleInfo = new RSMaterialComponent.RSButtonIconOne();
        btnDeleteRole = new RSMaterialComponent.RSButtonIconOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MainPanel.setBackground(new java.awt.Color(50, 51, 52));

        lblAdminProfiles.setForeground(new java.awt.Color(239, 96, 0));
        lblAdminProfiles.setText("Administrate Roles");
        lblAdminProfiles.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FINGERPRINT);

        tblUsers.setAutoCreateRowSorter(true);
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUsers.setBackgoundHead(new java.awt.Color(239, 96, 0));
        tblUsers.setBackgoundHover(new java.awt.Color(255, 137, 25));
        tblUsers.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tblUsers.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        btnClose.setBackground(new java.awt.Color(204, 0, 0));
        btnClose.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnClose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnUpdateList.setBackground(new java.awt.Color(239, 96, 0));
        btnUpdateList.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnUpdateList.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REFRESH);
        btnUpdateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateListActionPerformed(evt);
            }
        });

        tblRoles.setAutoCreateRowSorter(true);
        tblRoles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblRoles.setBackgoundHead(new java.awt.Color(239, 96, 0));
        tblRoles.setBackgoundHover(new java.awt.Color(255, 137, 25));
        tblRoles.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tblRoles.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tblRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRolesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRoles);

        btnCreateRole.setBackground(new java.awt.Color(239, 96, 0));
        btnCreateRole.setText("Create Role");
        btnCreateRole.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnCreateRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCreateRole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateRole.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnCreateRole.setPositionIcon(rojeru_san.efectos.ValoresEnum.POSITIONICON.RIGHT);
        btnCreateRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRoleActionPerformed(evt);
            }
        });

        btnAsignRole.setBackground(new java.awt.Color(239, 96, 0));
        btnAsignRole.setText("Asign Role");
        btnAsignRole.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnAsignRole.setEnabled(false);
        btnAsignRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAsignRole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsignRole.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FINGERPRINT);
        btnAsignRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignRoleActionPerformed(evt);
            }
        });

        btnRoleInfo.setBackground(new java.awt.Color(239, 96, 0));
        btnRoleInfo.setToolTipText("");
        btnRoleInfo.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnRoleInfo.setEnabled(false);
        btnRoleInfo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INFO_OUTLINE);
        btnRoleInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoleInfoActionPerformed(evt);
            }
        });

        btnDeleteRole.setBackground(new java.awt.Color(239, 96, 0));
        btnDeleteRole.setToolTipText("");
        btnDeleteRole.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnDeleteRole.setEnabled(false);
        btnDeleteRole.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnDeleteRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAdminProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(btnAsignRole, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCreateRole, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAdminProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.parent.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLanguageUI();
        fillUserTable(createUsersTablemodel());
        fillRolesTable(createRolesTablemodel());
    }//GEN-LAST:event_formWindowOpened
    
    private int userSelectedRow = -1;
    private int roleSelectedRow = -1;
    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        if(tblUsers.getSelectedRow() != userSelectedRow){
            userSelectedRow = tblUsers.getSelectedRow();
        }
        
        if(((String)tblUsers.getValueAt(userSelectedRow, 1)).equals("SYSADMIN")){
            this.btnAsignRole.setEnabled(false);
        }else{
            if(roleSelectedRow != -1 && userSelectedRow != -1){
                this.btnAsignRole.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tblUsersMouseClicked

    private void btnUpdateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateListActionPerformed
        userSelectedRow = -1;
        tblUsers.clearSelection();
        tblRoles.clearSelection();
        fillUserTable(createUsersTablemodel());
        fillRolesTable(createRolesTablemodel());
        this.btnRoleInfo.setEnabled(false);
        this.btnAsignRole.setEnabled(false);
        this.btnDeleteRole.setEnabled(false);
    }//GEN-LAST:event_btnUpdateListActionPerformed

    private void tblRolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRolesMouseClicked
        if(tblRoles.getSelectedRow() != roleSelectedRow){
            roleSelectedRow = tblRoles.getSelectedRow();
        }
        
        if(roleSelectedRow != -1 && userSelectedRow != -1){
            this.btnAsignRole.setEnabled(true);
        }
        
        if(roleSelectedRow != -1){
            this.btnRoleInfo.setEnabled(true);
            if(((String)tblRoles.getValueAt(roleSelectedRow, 1)).equals("USER") || ((String)tblRoles.getValueAt(roleSelectedRow, 1)).equals("SYSADMIN")){
                //Roles USER y SYSADMIN no se pueden eliminar
                this.btnDeleteRole.setEnabled(false);
            }else{
                this.btnDeleteRole.setEnabled(true);
                try{
                    if(((String)tblUsers.getValueAt(userSelectedRow, 1)).equals("SYSADMIN")){ //Si se selecciona el usuario SYSADMIN
                        this.btnAsignRole.setEnabled(false);
                    }
                }catch(Exception e){}
            }
        }
    }//GEN-LAST:event_tblRolesMouseClicked

    private void btnCreateRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRoleActionPerformed
        CreateRoleGUI creRolGui = new CreateRoleGUI(this, true);
        creRolGui.setVisible(true);
        fillRolesTable(createRolesTablemodel());
    }//GEN-LAST:event_btnCreateRoleActionPerformed

    private void btnRoleInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoleInfoActionPerformed
        Role role = new Role();
        LinkedList<domain.Permission> perms = role.getDao().getPermissionList((String)tblRoles.getValueAt(roleSelectedRow, 1));
        String texto = "";
        for(int i = 0; i < perms.size(); i++)
            texto+=perms.get(i).getPermname()+"\n";
        utilities.MsgBox.create(this, texto, utilities.MsgBox.INFO_ICON).setVisible(true);
    }//GEN-LAST:event_btnRoleInfoActionPerformed

    private void btnAsignRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignRoleActionPerformed
        RegistredUser u = new RegistredUser();
        int userid = (int)tblUsers.getValueAt(userSelectedRow, 0);
        int roleid = (int)tblRoles.getValueAt(roleSelectedRow, 0);
        u.getDao().setRole(userid, roleid);
        
        btnUpdateList.doClick();
    }//GEN-LAST:event_btnAsignRoleActionPerformed

    private void btnDeleteRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoleActionPerformed
        Role r = new Role();
        int roleid = (int)tblRoles.getValueAt(roleSelectedRow, 0);
        r.getDao().deleteRole(roleid);
        btnUpdateList.doClick();        
    }//GEN-LAST:event_btnDeleteRoleActionPerformed

    private DefaultTableModel createRolesTablemodel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(PropertiesController.getLangValue("roleid"));
        model.addColumn(PropertiesController.getLangValue("rolename"));
        return model;
    }
    
    private void fillRolesTable(DefaultTableModel model){
        //recoge datos de usuarios del servidor
        LinkedList<Role> roles = (new Role()).getDao().getRoleList();
        //añade los datos al table model
        for(int i = 0; i < roles.size(); i++){                
            Object[] rowData = new Object[]{
                roles.get(i).getIdRole(),
                roles.get(i).getRolename()
            };
            model.addRow(rowData);
        }
        //asigna el table model a la tabla
        this.tblRoles.setModel(model);
    }
    
    private DefaultTableModel createUsersTablemodel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(PropertiesController.getLangValue("userid"));
        model.addColumn(PropertiesController.getLangValue("username"));
        model.addColumn(PropertiesController.getLangValue("role"));
        return model;
    }
    
    private void fillUserTable(DefaultTableModel model){
        //recoge datos de usuarios del servidor
        LinkedList<RegistredUser> users = myUser.getDao().getUsersList();
        //añade los datos al table model
        for(int i = 0; i < users.size(); i++){                
            Object[] rowData = new Object[]{
                users.get(i).getIdUser(),
                users.get(i).getUsername(),
                users.get(i).getRole()
            };
            model.addRow(rowData);
        }
        //asigna el table model a la tabla
        this.tblUsers.setModel(model);
    }
    
    private void setLanguageUI(){
        this.lblAdminProfiles.setText(PropertiesController.getLangValue("administrateroles"));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRolesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRolesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRolesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRolesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRolesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private RSMaterialComponent.RSButtonMaterialIconOne btnAsignRole;
    private RSMaterialComponent.RSButtonIconOne btnClose;
    private RSMaterialComponent.RSButtonMaterialIconOne btnCreateRole;
    private RSMaterialComponent.RSButtonIconOne btnDeleteRole;
    private RSMaterialComponent.RSButtonIconOne btnRoleInfo;
    private RSMaterialComponent.RSButtonIconOne btnUpdateList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSLabelTextIcon lblAdminProfiles;
    private RSMaterialComponent.RSTableMetroCustom tblRoles;
    private RSMaterialComponent.RSTableMetroCustom tblUsers;
    // End of variables declaration//GEN-END:variables
}
