/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.util.Locale;
import javax.swing.JFrame;
import persistence.ClientPreferencesAdmin;
import persistence.LanguageController;

/**
 *
 * @author erome
 */
public class ClientPreferencesGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientPreferencesGUI
     */
    public ClientPreferencesGUI() {
        initComponents();
    }
    
    private JFrame parent;
    public ClientPreferencesGUI(JFrame parent) {
        initComponents();
        this.parent = parent;
        this.parent.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        lblPreferneces = new RSMaterialComponent.RSLabelTextIcon();
        swLanguage = new RSMaterialComponent.RSSwitch();
        lblLanguage = new RSMaterialComponent.RSLabelTextIcon();
        lblSpanish = new javax.swing.JLabel();
        lblEnglish = new javax.swing.JLabel();
        btnClose = new RSMaterialComponent.RSButtonIconOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MainPanel.setBackground(new java.awt.Color(50, 51, 52));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 96, 0), 3));

        lblPreferneces.setForeground(new java.awt.Color(239, 96, 0));
        lblPreferneces.setText("Preferences");
        lblPreferneces.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS);

        swLanguage.setActivado(false);
        swLanguage.setBgOn(new java.awt.Color(239, 96, 0));
        swLanguage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                swLanguageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                swLanguageMousePressed(evt);
            }
        });

        lblLanguage.setForeground(new java.awt.Color(239, 96, 0));
        lblLanguage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLanguage.setText("Language");
        lblLanguage.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LANGUAGE);

        lblSpanish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icono_idioma_espanol_redim.jpg"))); // NOI18N

        lblEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icono_idioma_ingles_redim.png"))); // NOI18N

        btnClose.setBackground(new java.awt.Color(204, 0, 0));
        btnClose.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnClose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblPreferneces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblEnglish)
                        .addGap(18, 18, 18)
                        .addComponent(swLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSpanish)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPreferneces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSpanish)
                            .addComponent(lblEnglish)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(swLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void swLanguageState(){
        if(ClientPreferencesAdmin.getInstance().getLocale().equals(Locale.ENGLISH))
            swLanguage.setActivado(false);
        else
            swLanguage.setActivado(true);
    }
    
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.parent.setEnabled(true);
        ((MenuGUI) parent).setLanguageUI();
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        swLanguageState();
        setLanguageUI();
    }//GEN-LAST:event_formWindowOpened

    private void swLanguageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_swLanguageMousePressed
        
    }//GEN-LAST:event_swLanguageMousePressed

    private void swLanguageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_swLanguageMouseClicked
        if(swLanguage.isActivado()){
            ClientPreferencesAdmin.getInstance().setLocale("es_ES");
        }else{
           ClientPreferencesAdmin.getInstance().setLocale("en_EN"); 
        }
        setLanguageUI();
    }//GEN-LAST:event_swLanguageMouseClicked

    private void setLanguageUI(){
        this.lblPreferneces.setText(LanguageController.getLangValue("preferences"));
        this.lblLanguage.setText(LanguageController.getLangValue("language"));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientPreferencesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientPreferencesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientPreferencesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientPreferencesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientPreferencesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private RSMaterialComponent.RSButtonIconOne btnClose;
    private javax.swing.JLabel lblEnglish;
    private RSMaterialComponent.RSLabelTextIcon lblLanguage;
    private RSMaterialComponent.RSLabelTextIcon lblPreferneces;
    private javax.swing.JLabel lblSpanish;
    private RSMaterialComponent.RSSwitch swLanguage;
    // End of variables declaration//GEN-END:variables
}
