/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Permission;
import domain.Role;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import utilities.PropertiesController;

/**
 *
 * @author erome
 */
public class CreateRoleGUI extends javax.swing.JDialog {

    /**
     * Creates new form CreateRoleGUI
     */
    public CreateRoleGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        btnClose = new RSMaterialComponent.RSButtonIconOne();
        lblCreateRole = new RSMaterialComponent.RSLabelTextIcon();
        txtRolename = new RSMaterialComponent.RSTextFieldMaterialIcon();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        rSButtonIconOne2 = new RSMaterialComponent.RSButtonIconOne();
        btnFinish = new RSMaterialComponent.RSButtonMaterialIconOne();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAvailablePermissions = new RSMaterialComponent.RSTableMetroCustom();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSelectedPermissions = new RSMaterialComponent.RSTableMetroCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(50, 51, 52));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 96, 0), 2));

        btnClose.setBackground(new java.awt.Color(204, 0, 0));
        btnClose.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnClose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblCreateRole.setForeground(new java.awt.Color(239, 96, 0));
        lblCreateRole.setText("Create Role");
        lblCreateRole.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FINGERPRINT);

        txtRolename.setForeground(new java.awt.Color(239, 96, 0));
        txtRolename.setColorIcon(new java.awt.Color(239, 96, 0));
        txtRolename.setColorMaterial(new java.awt.Color(239, 96, 0));
        txtRolename.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INPUT);
        txtRolename.setPhColor(new java.awt.Color(239, 96, 0));
        txtRolename.setPlaceholder("Role Name");

        rSButtonIconOne1.setBackground(new java.awt.Color(239, 96, 0));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(255, 137, 25));
        rSButtonIconOne1.setEnabled(false);
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_FORWARD);

        rSButtonIconOne2.setBackground(new java.awt.Color(239, 96, 0));
        rSButtonIconOne2.setBackgroundHover(new java.awt.Color(255, 137, 25));
        rSButtonIconOne2.setEnabled(false);
        rSButtonIconOne2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);

        btnFinish.setBackground(new java.awt.Color(239, 96, 0));
        btnFinish.setText("Finish");
        btnFinish.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnFinish.setEnabled(false);
        btnFinish.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFinish.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK);

        tblAvailablePermissions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAvailablePermissions.setBackgoundHead(new java.awt.Color(239, 96, 0));
        tblAvailablePermissions.setBackgoundHover(new java.awt.Color(255, 137, 25));
        jScrollPane3.setViewportView(tblAvailablePermissions);

        tblSelectedPermissions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSelectedPermissions.setBackgoundHead(new java.awt.Color(239, 96, 0));
        tblSelectedPermissions.setBackgoundHover(new java.awt.Color(255, 137, 25));
        tblSelectedPermissions.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tblSelectedPermissions.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(tblSelectedPermissions);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSButtonIconOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButtonIconOne2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(lblCreateRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(txtRolename, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCreateRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRolename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(rSButtonIconOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(rSButtonIconOne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLanguageUI();
        fillAvailablePermissionsTable(createPermissionsTablemodel());
        tblSelectedPermissions.setModel(createPermissionsTablemodel());
    }//GEN-LAST:event_formWindowOpened

    private void setLanguageUI(){
        
    }
    
    private DefaultTableModel createPermissionsTablemodel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(PropertiesController.getLangValue("permid"));
        model.addColumn(PropertiesController.getLangValue("permname"));
        return model;
    }
    
    private void fillAvailablePermissionsTable(DefaultTableModel model){
        //recoge datos de usuarios del servidor
        LinkedList<Permission> perms = new LinkedList<>() ;
        //añade los datos al table model
        for(int i = 0; i < perms.size(); i++){                
            Object[] rowData = new Object[]{
                perms.get(i).getIdPermission(),
                perms.get(i).getPermname()
            };
            model.addRow(rowData);
        }
        //asigna el table model a la tabla
        this.tblAvailablePermissions.setModel(model);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRoleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRoleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRoleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRoleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateRoleGUI dialog = new CreateRoleGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnClose;
    private RSMaterialComponent.RSButtonMaterialIconOne btnFinish;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private RSMaterialComponent.RSLabelTextIcon lblCreateRole;
    private javax.swing.JPanel mainPanel;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne2;
    private RSMaterialComponent.RSTableMetroCustom tblAvailablePermissions;
    private RSMaterialComponent.RSTableMetroCustom tblSelectedPermissions;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtRolename;
    // End of variables declaration//GEN-END:variables
}
