/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.RegistredUser;
import java.awt.Toolkit;
import javax.swing.JFrame;
import utilities.MsgBox;
import utilities.PropertiesController;

/**
 *
 * @author erome
 */
public class CreateUserGUI extends javax.swing.JDialog {

    private RegistredUser myUser;
    private JFrame parent;
    
    public CreateUserGUI(java.awt.Frame parent,RegistredUser myUser, boolean modal) {
        this(parent, modal);
        this.myUser = myUser;
        this.parent = (JFrame)parent;
    }
    
    public CreateUserGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setProgramIcon();
    }
    private void setProgramIcon(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("resources/client_icon_32.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCreateNewUser = new RSMaterialComponent.RSLabelTextIcon();
        btnAccept = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnCancel = new RSMaterialComponent.RSButtonMaterialIconOne();
        txtUsername = new RSMaterialComponent.RSTextFieldMaterialIcon();
        txtUserEmail = new RSMaterialComponent.RSTextFieldMaterialIcon();
        lblPasswordInfo = new javax.swing.JLabel();
        lblRoleInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 51, 52));

        lblCreateNewUser.setForeground(new java.awt.Color(239, 96, 0));
        lblCreateNewUser.setText("Create New User");

        btnAccept.setBackground(new java.awt.Color(239, 96, 0));
        btnAccept.setText("Accept");
        btnAccept.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnAccept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAccept.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK);
        btnAccept.setPositionIcon(rojeru_san.efectos.ValoresEnum.POSITIONICON.RIGHT);
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(239, 96, 0));
        btnCancel.setText("Cancel");
        btnCancel.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtUsername.setForeground(new java.awt.Color(239, 96, 0));
        txtUsername.setColorIcon(new java.awt.Color(239, 96, 0));
        txtUsername.setColorMaterial(new java.awt.Color(239, 96, 0));
        txtUsername.setPhColor(new java.awt.Color(239, 96, 0));
        txtUsername.setPlaceholder("Username");

        txtUserEmail.setForeground(new java.awt.Color(239, 96, 0));
        txtUserEmail.setColorIcon(new java.awt.Color(239, 96, 0));
        txtUserEmail.setColorMaterial(new java.awt.Color(239, 96, 0));
        txtUserEmail.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MAIL_OUTLINE);
        txtUserEmail.setPhColor(new java.awt.Color(239, 96, 0));
        txtUserEmail.setPlaceholder("User Email");

        lblPasswordInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPasswordInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordInfo.setText("Password Will Be Generated Automatically");

        lblRoleInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRoleInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblRoleInfo.setText("Role USER Will Be Set By Default");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateNewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasswordInfo)
                            .addComponent(lblRoleInfo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblRoleInfo)
                .addGap(18, 18, 18)
                .addComponent(lblPasswordInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLanguageUI();
    }//GEN-LAST:event_formWindowOpened

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        boolean result = myUser.getDao().createNewUser(txtUsername.getText(), txtUserEmail.getText());
        if(!result)
            MsgBox.create(this.parent, PropertiesController.getLangValue("error_insert_user").replaceAll("-", "\n"), MsgBox.ERROR_ICON);
        else
            this.dispose();
    }//GEN-LAST:event_btnAcceptActionPerformed
    
    private void setLanguageUI(){
        this.txtUsername.setPlaceholder(PropertiesController.getLangValue("username"));
        this.txtUserEmail.setPlaceholder(PropertiesController.getLangValue("useremail"));
        this.lblCreateNewUser.setText(PropertiesController.getLangValue("createnewuser"));
        this.lblRoleInfo.setText(PropertiesController.getLangValue("roleinfo_createuser"));
        this.lblPasswordInfo.setText(PropertiesController.getLangValue("passwordinfo_createuser"));
        this.btnAccept.setText(PropertiesController.getLangValue("accept"));
        this.btnCancel.setText(PropertiesController.getLangValue("cancel"));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateUserGUI dialog = new CreateUserGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnAccept;
    private RSMaterialComponent.RSButtonMaterialIconOne btnCancel;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSLabelTextIcon lblCreateNewUser;
    private javax.swing.JLabel lblPasswordInfo;
    private javax.swing.JLabel lblRoleInfo;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtUserEmail;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtUsername;
    // End of variables declaration//GEN-END:variables
}
