/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author erome
 */
public class InMailGUI extends javax.swing.JFrame {

    private JFrame parent;
    public InMailGUI(JFrame parent) {
        this();
        //this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        this.parent = parent;
    }
    
    public InMailGUI() {
        initComponents();
        prueba();
    }
    
    public void prueba(){
        //uso vertical layout para colocar una encima de otra
        InMailCard card1 = new InMailCard("pepe", "asunto", "contenido del email", false, new Date(), this.ReadingPanel);
        InMailCard card2 = new InMailCard("juan", "asuntillo", "esto es un mensaje de juan", false, new Date(), this.ReadingPanel);
        InMailCard card3 = new InMailCard("juan2", "asuntillo", "esto es un mensaje de juan", false, new Date(), this.ReadingPanel);
        InMailCard card4 = new InMailCard("juan3", "asuntillo", "esto es un mensaje de juan", false, new Date(), this.ReadingPanel);
        InMailCard card5 = new InMailCard("juan4", "asuntillo", "esto es un mensaje de juan", false, new Date(), this.ReadingPanel);
        InMailCard card6 = new InMailCard("pepe2", "asunto", "contenido del email", false, new Date(), this.ReadingPanel);
        
        //Actualizo el panel interno del scroll
        this.MailPanel.removeAll();
        this.MailPanel.add(card1);
        this.MailPanel.add(card2);  
        this.MailPanel.add(card3); 
        this.MailPanel.add(card4); 
        this.MailPanel.add(card5);
        this.MailPanel.add(card6);
        //this.MailPanel.revalidate();
        //this.MailPanel.repaint();
        
        
        //aqui deberia actualizar el scroll panel //aqui estan los problemas
        MailScroll.setViewportView(this.MailPanel);  
        MailScroll.revalidate();  
        MailScroll.repaint();  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReadingPanel = new javax.swing.JPanel();
        ControlPanel = new javax.swing.JPanel();
        btnCloseInMail = new RSMaterialComponent.RSButtonIconOne();
        btnWriteInMail = new RSMaterialComponent.RSButtonIconOne();
        btnUpdate = new RSMaterialComponent.RSButtonIconOne();
        MailScroll = new javax.swing.JScrollPane();
        MailPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ReadingPanel.setBackground(new java.awt.Color(204, 204, 255));
        ReadingPanel.setLayout(new org.jdesktop.swingx.VerticalLayout());

        ControlPanel.setBackground(new java.awt.Color(37, 45, 223));

        btnCloseInMail.setBackground(new java.awt.Color(204, 0, 0));
        btnCloseInMail.setBackgroundHover(new java.awt.Color(204, 0, 0));
        btnCloseInMail.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnCloseInMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseInMailActionPerformed(evt);
            }
        });

        btnWriteInMail.setToolTipText("Write New In Mail");
        btnWriteInMail.setBackgroundHover(new java.awt.Color(0, 0, 153));
        btnWriteInMail.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);

        btnUpdate.setToolTipText("Update In Box");
        btnUpdate.setBackgroundHover(new java.awt.Color(0, 0, 153));
        btnUpdate.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                .addComponent(btnWriteInMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseInMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCloseInMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWriteInMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MailScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        MailScroll.setMinimumSize(new java.awt.Dimension(210, 437));
        MailScroll.setPreferredSize(new java.awt.Dimension(210, 437));

        MailPanel.setBackground(new java.awt.Color(153, 153, 255));
        MailPanel.setMinimumSize(new java.awt.Dimension(210, 437));
        MailPanel.setPreferredSize(new java.awt.Dimension(210, 437));
        MailPanel.setLayout(new org.jdesktop.swingx.VerticalLayout());
        MailScroll.setViewportView(MailPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MailScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReadingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ReadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(MailScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseInMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseInMailActionPerformed
        this.parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseInMailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InMailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InMailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InMailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InMailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InMailGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel MailPanel;
    private javax.swing.JScrollPane MailScroll;
    private javax.swing.JPanel ReadingPanel;
    private RSMaterialComponent.RSButtonIconOne btnCloseInMail;
    private RSMaterialComponent.RSButtonIconOne btnUpdate;
    private RSMaterialComponent.RSButtonIconOne btnWriteInMail;
    // End of variables declaration//GEN-END:variables
}
