/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.util.Date;
import javax.swing.JFrame;
import org.jdesktop.swingx.VerticalLayout;

/**
 *
 * @author erome
 */
public class InMailGUI extends javax.swing.JFrame {

    private JFrame parent;
    public InMailGUI(JFrame parent) {
        this();
        //this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        this.parent = parent;
    }
    
    public InMailGUI() {
        initComponents();
        refresh();
        //se llamará a refresh
    }
    
    private InMailCard createInMailCard(String source, String subject, String content, boolean readed, Date date){
        return new InMailCard(source, subject, content, readed, date, this.ReadingPanel);
    }
    
    private void addInMailCard(InMailCard card){
        this.MailPanel.add(card);
    }
    
    private void create_addInMailCard(String source, String subject, String content, boolean readed, Date date){
        addInMailCard(createInMailCard(source, subject, content, readed, date));
    }
    
    public void refresh(){
        this.MailPanel.removeAll();
        VerticalLayout vert = new VerticalLayout();
        this.MailPanel.setLayout(vert);
        
        //Añado las tarjetas
        prueba();
        
        this.MailPanel.revalidate();
        this.MailPanel.repaint();
    }
    
    public void prueba(){
        create_addInMailCard("Pepe", "Asunto de pepe", "Contenido del mensaje de pepe", false, new Date());
        create_addInMailCard("Jose", "Asunto de jose", "Contenido del mensaje de jose", false, new Date());
        create_addInMailCard("Juan", "Asunto de juan", "Contenido del mensaje de juan", false, new Date());
        create_addInMailCard("Manolo", "Asunto de manolo", "Contenido del mensaje de manolo", false, new Date());
        create_addInMailCard("Loren Ipsum", "Asunto de Loren Ipsum", "Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum "
                + "Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum "
                + "Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum Loren Ipsum \n\n"
                + "Loren Ipsum Loren Ipsum Loren Ipsum ", false, new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControlPanel = new javax.swing.JPanel();
        btnCloseInMail = new RSMaterialComponent.RSButtonIconOne();
        btnWriteInMail = new RSMaterialComponent.RSButtonIconOne();
        btnUpdate = new RSMaterialComponent.RSButtonIconOne();
        ScrollPanel = new javax.swing.JScrollPane();
        MailPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ReadingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ControlPanel.setBackground(new java.awt.Color(239, 96, 0));

        btnCloseInMail.setBackground(new java.awt.Color(204, 0, 0));
        btnCloseInMail.setText("Close This Window");
        btnCloseInMail.setBackgroundHover(new java.awt.Color(204, 0, 0));
        btnCloseInMail.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnCloseInMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseInMailActionPerformed(evt);
            }
        });

        btnWriteInMail.setBackground(new java.awt.Color(239, 96, 0));
        btnWriteInMail.setToolTipText("Write New InMail");
        btnWriteInMail.setBackgroundHover(new java.awt.Color(0, 0, 153));
        btnWriteInMail.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);

        btnUpdate.setBackground(new java.awt.Color(239, 96, 0));
        btnUpdate.setToolTipText("Update Inbox");
        btnUpdate.setBackgroundHover(new java.awt.Color(0, 0, 153));
        btnUpdate.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                .addComponent(btnWriteInMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseInMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCloseInMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWriteInMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        MailPanel.setBackground(new java.awt.Color(239, 96, 0));
        MailPanel.setLayout(new org.jdesktop.swingx.VerticalLayout());
        ScrollPanel.setViewportView(MailPanel);

        jPanel1.setBackground(new java.awt.Color(50, 51, 52));

        ReadingPanel.setBackground(new java.awt.Color(255, 255, 255));
        ReadingPanel.setLayout(new org.jdesktop.swingx.VerticalLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(ReadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseInMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseInMailActionPerformed
        this.parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseInMailActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        refresh();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InMailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InMailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InMailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InMailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InMailGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel MailPanel;
    private javax.swing.JPanel ReadingPanel;
    private javax.swing.JScrollPane ScrollPanel;
    private RSMaterialComponent.RSButtonIconOne btnCloseInMail;
    private RSMaterialComponent.RSButtonIconOne btnUpdate;
    private RSMaterialComponent.RSButtonIconOne btnWriteInMail;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
