/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import persistence.LanguageController;
import utilities.Encrypt;
import utilities.MsgBox;

/**
 *
 * @author erome
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginGUI() {
        initComponents();
        checkFirstRunning();
    }
    
    private void checkFirstRunning(){
        if(!(new File("./clientfiles/client.cconf")).exists())
            new FirstRunningGUI().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        txtUserPassword = new RSMaterialComponent.RSPasswordMaterialIcon();
        txtUserName = new RSMaterialComponent.RSTextFieldIconOne();
        lblTitle = new RSMaterialComponent.RSLabelTextIcon();
        btnLogin = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnExit = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnConfigClient = new RSMaterialComponent.RSButtonIconShadow();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MainPanel.setBackground(new java.awt.Color(50, 51, 52));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 96, 0), 3));

        txtUserPassword.setForeground(new java.awt.Color(239, 96, 0));
        txtUserPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUserPassword.setColorIcon(new java.awt.Color(239, 96, 0));
        txtUserPassword.setColorMaterial(new java.awt.Color(239, 96, 0));
        txtUserPassword.setPhColor(new java.awt.Color(239, 96, 0));
        txtUserPassword.setPlaceholder("User Password");
        txtUserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserPasswordKeyPressed(evt);
            }
        });

        txtUserName.setForeground(new java.awt.Color(239, 96, 0));
        txtUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUserName.setBorderColor(new java.awt.Color(255, 255, 255));
        txtUserName.setColorIcon(new java.awt.Color(239, 96, 0));
        txtUserName.setPhColor(new java.awt.Color(239, 96, 0));
        txtUserName.setPlaceholder("User Name");
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });

        lblTitle.setForeground(new java.awt.Color(239, 96, 0));
        lblTitle.setText("User Login");
        lblTitle.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.POWER_SETTINGS_NEW);

        btnLogin.setBackground(new java.awt.Color(239, 96, 0));
        btnLogin.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnLogin.setText("Log In");
        btnLogin.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCK_OPEN);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(239, 96, 0));
        btnExit.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnExit.setText("Exit");
        btnExit.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnConfigClient.setBackground(new java.awt.Color(239, 96, 0));
        btnConfigClient.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnConfigClient.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PUBLIC);
        btnConfigClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfigClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                        .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfigClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            persistence.ConnectionClient connection = new persistence.ConnectionClient(txtUserName.getText(), Encrypt.encriptar_DESede(new String(txtUserPassword.getPassword())));
            if(connection.getConnectionResult() != -1){
                MenuGUI menu = new MenuGUI(txtUserName.getText(), connection.getRolename(), connection.getConnectionResult(), this);
                this.setVisible(false);
                this.txtUserName.setText(""); //Limpio los campos si los datos se han introducido correctamente
                this.txtUserPassword.setText("");
                menu.setVisible(true);
            }else{
                MsgBox.create(this, connection.getConnectionResultMessage(), MsgBox.INFO_ICON).setVisible(true);
            }
        } catch (IOException ex) {
            MsgBox.create(this, "Could Not Create Connection Client", MsgBox.ERROR_ICON).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnConfigClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigClientActionPerformed
        ConnectionConfiguratorGUI cc = new ConnectionConfiguratorGUI(this);
        cc.setVisible(true);
    }//GEN-LAST:event_btnConfigClientActionPerformed

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             btnLogin.doClick();
         }
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void txtUserPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserPasswordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             btnLogin.doClick();
         }
    }//GEN-LAST:event_txtUserPasswordKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLanguageUI();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private RSMaterialComponent.RSButtonIconShadow btnConfigClient;
    private RSMaterialComponent.RSButtonMaterialIconOne btnExit;
    private RSMaterialComponent.RSButtonMaterialIconOne btnLogin;
    private RSMaterialComponent.RSLabelTextIcon lblTitle;
    private RSMaterialComponent.RSTextFieldIconOne txtUserName;
    private RSMaterialComponent.RSPasswordMaterialIcon txtUserPassword;
    // End of variables declaration//GEN-END:variables

    void setLanguageUI() {
        this.lblTitle.setText(LanguageController.getLangValue("userlogin"));
        this.txtUserName.setPlaceholder(LanguageController.getLangValue("username"));
        this.txtUserPassword.setPlaceholder(LanguageController.getLangValue("userpassword"));
        this.btnLogin.setText(LanguageController.getLangValue("login"));
        this.btnExit.setText(LanguageController.getLangValue("exit"));
    }
}
