/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Product;
import domain.RegistredUser;
import domain.Ticket;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import utilities.PropertiesController;

/**
 *
 * @author erome
 */
public class NewSaleGUI extends javax.swing.JDialog {
   
    private RegistredUser myUser;
    
    public NewSaleGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillProductsCombo();
        tblTicket.setModel(createTableModel());
    }
    
    public NewSaleGUI(java.awt.Frame parent, boolean modal, RegistredUser myUser) {
        this(parent, modal);
        this.myUser = myUser;
    }
    
    private DefaultTableModel createTableModel(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn(PropertiesController.getLangValue("productname"));
        model.addColumn(PropertiesController.getLangValue("units"));
        model.addColumn(PropertiesController.getLangValue("unitprice"));
       
        return model;
    }
    
    private void fillProductsCombo(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        Product p = new Product();

        for(Product prod : p.getDao().getProductsList())
            if(!prod.isDeleted())
                model.addElement(prod.getProductname());
        
        cboxProducts.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNewSale = new RSMaterialComponent.RSLabelTextIcon();
        btnClose = new RSMaterialComponent.RSButtonIconOne();
        lblAddProduct = new RSMaterialComponent.RSLabelTextIcon();
        lblTicket = new RSMaterialComponent.RSLabelTextIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicket = new RSMaterialComponent.RSTableMetroCustom();
        btnPrintTicket = new RSMaterialComponent.RSButtonMaterialOne();
        btnRemoveFromTicket = new RSMaterialComponent.RSButtonMaterialOne();
        jPanel2 = new javax.swing.JPanel();
        txtUnitPrice = new RSMaterialComponent.RSTextFieldMaterial();
        lblUnits = new javax.swing.JLabel();
        cboxProducts = new RSMaterialComponent.RSComboBoxMaterial();
        lblUnitPrice = new javax.swing.JLabel();
        txtUnits = new RSMaterialComponent.RSTextFieldMaterial();
        btnAddToTicket = new RSMaterialComponent.RSButtonMaterialOne();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 51, 52));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 96, 0), 2));

        lblNewSale.setForeground(new java.awt.Color(239, 96, 0));
        lblNewSale.setText("New Sale");
        lblNewSale.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);

        btnClose.setBackground(new java.awt.Color(204, 0, 0));
        btnClose.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnClose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblAddProduct.setForeground(new java.awt.Color(239, 96, 0));
        lblAddProduct.setText("Add Product");
        lblAddProduct.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);

        lblTicket.setForeground(new java.awt.Color(239, 96, 0));
        lblTicket.setText("Ticket");
        lblTicket.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RECEIPT);

        tblTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblTicket.setBackgoundHead(new java.awt.Color(239, 96, 0));
        tblTicket.setBackgoundHover(new java.awt.Color(239, 96, 0));
        tblTicket.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tblTicket.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tblTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTicketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTicket);

        btnPrintTicket.setBackground(new java.awt.Color(239, 96, 0));
        btnPrintTicket.setText("Print Ticket");
        btnPrintTicket.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnPrintTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintTicketActionPerformed(evt);
            }
        });

        btnRemoveFromTicket.setBackground(new java.awt.Color(239, 96, 0));
        btnRemoveFromTicket.setText("Remove Product");
        btnRemoveFromTicket.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnRemoveFromTicket.setEnabled(false);
        btnRemoveFromTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromTicketActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(50, 51, 52));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        txtUnitPrice.setForeground(new java.awt.Color(0, 0, 0));
        txtUnitPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnitPrice.setText("0");
        txtUnitPrice.setColorMaterial(new java.awt.Color(239, 96, 0));
        txtUnitPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnitPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnitPriceFocusLost(evt);
            }
        });
        txtUnitPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnitPriceKeyTyped(evt);
            }
        });

        lblUnits.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUnits.setForeground(new java.awt.Color(255, 255, 255));
        lblUnits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnits.setText("Units");

        cboxProducts.setColorMaterial(new java.awt.Color(239, 96, 0));
        cboxProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxProductsActionPerformed(evt);
            }
        });

        lblUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUnitPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblUnitPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnitPrice.setText("Unit Price");

        txtUnits.setForeground(new java.awt.Color(0, 0, 0));
        txtUnits.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnits.setText("1");
        txtUnits.setColorMaterial(new java.awt.Color(239, 96, 0));
        txtUnits.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnitsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnitsFocusLost(evt);
            }
        });
        txtUnits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnitsKeyTyped(evt);
            }
        });

        btnAddToTicket.setBackground(new java.awt.Color(239, 96, 0));
        btnAddToTicket.setText("Add To Ticket");
        btnAddToTicket.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnAddToTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToTicketActionPerformed(evt);
            }
        });

        rSLabelIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EURO_SYMBOL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddToTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lblUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(lblUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSLabelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUnits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUnitPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSLabelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddToTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNewSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 18, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnPrintTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(btnRemoveFromTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNewSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52)
                        .addComponent(btnRemoveFromTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrintTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddToTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToTicketActionPerformed
        DefaultTableModel model = (DefaultTableModel)tblTicket.getModel();
        boolean yaExiste = false;
        for(int i = 0; i < model.getRowCount() && !yaExiste; i++){
            if(model.getValueAt(i, 0).equals((String)cboxProducts.getSelectedItem())){
                model.setValueAt((int) model.getValueAt(i, 1)+Integer.parseInt(txtUnits.getText()), i, 1);
                yaExiste = true;
            }
        }
        if(!yaExiste){ 
            Object[] row = new Object[]{(String)cboxProducts.getSelectedItem(), Integer.parseInt(txtUnits.getText()), Double.parseDouble(txtUnitPrice.getText())};
            model.addRow(row);
        }
        tblTicket.setModel(model);
    }//GEN-LAST:event_btnAddToTicketActionPerformed

    private void cboxProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxProductsActionPerformed
        getProductPrice();
    }//GEN-LAST:event_cboxProductsActionPerformed

    private void getProductPrice(){
        Product p = new Product();
        txtUnitPrice.setText(Double.toString(p.getDao().getProductPrice((String)cboxProducts.getSelectedItem())));
    }
    
    private void btnRemoveFromTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromTicketActionPerformed
        DefaultTableModel model = (DefaultTableModel)tblTicket.getModel();       
        model.removeRow(tblTicket.getSelectedRow());
        tblTicket.setModel(model);
        tblTicket.clearSelection();
        btnRemoveFromTicket.setEnabled(false);
    }//GEN-LAST:event_btnRemoveFromTicketActionPerformed

    private void tblTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTicketMouseClicked
        if(tblTicket.getSelectedRow() != -1){
            btnRemoveFromTicket.setEnabled(true);
        }
    }//GEN-LAST:event_tblTicketMouseClicked

    private void btnPrintTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintTicketActionPerformed
        if(tblTicket.getRowCount() > 0){
            Ticket t = new Ticket(myUser.getIdUser());
            for(int i = 0; i < tblTicket.getRowCount(); i++){
                String pName = (String)tblTicket.getValueAt(i, 0);
                int pUnit = (int)tblTicket.getValueAt(i, 1);
                double pUnitPrice = (double)tblTicket.getValueAt(i, 2);
                t.add(pName, pUnit, pUnitPrice);
            }
            t.confirmTicket();
        }
        //Generate report
        
        
        //Show report
        
        
        //close 
        this.dispose();
    }//GEN-LAST:event_btnPrintTicketActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLanguageUI();
        getProductPrice();
    }//GEN-LAST:event_formWindowOpened

    private void txtUnitsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnitsFocusGained
        txtUnits.selectAll();
    }//GEN-LAST:event_txtUnitsFocusGained

    private void txtUnitPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnitPriceFocusGained
        txtUnitPrice.selectAll();
    }//GEN-LAST:event_txtUnitPriceFocusGained

    private void txtUnitsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnitsKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
           (c == KeyEvent.VK_BACK_SPACE) ||
           (c == KeyEvent.VK_DELETE))) {
          getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_txtUnitsKeyTyped

    private void txtUnitPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnitPriceKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
           (c == KeyEvent.VK_BACK_SPACE) ||
           (c == KeyEvent.VK_DELETE) ||
                (c == '.') || (c == ','))) {
          getToolkit().beep();
          evt.consume();
        }
        boolean dot = txtUnitPrice.getText().contains("."); //Si existe un '.' previamente
        if(c == ','){
            evt.setKeyChar('.');
            c = evt.getKeyChar();
        }
        if(c == '.' && dot){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtUnitPriceKeyTyped

    private void txtUnitPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnitPriceFocusLost
        String price = txtUnitPrice.getText();
        double parser = Double.parseDouble(price);
        parser = round(parser, 2);
        txtUnitPrice.setText(Double.toString(parser));
    }//GEN-LAST:event_txtUnitPriceFocusLost

    private void txtUnitsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnitsFocusLost
        String units = txtUnits.getText();
        int u = Integer.parseInt(units);
        if(u < 1)
            u = 1;
        txtUnits.setText(Integer.toString(u));
    }//GEN-LAST:event_txtUnitsFocusLost

    public static double round(double value, int places) {
        if (places < 0) throw new IllegalArgumentException();

        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }
    
    private void setLanguageUI(){
        this.lblNewSale.setText(PropertiesController.getLangValue("newsale"));
        this.lblAddProduct.setText(PropertiesController.getLangValue("addproduct"));
        this.lblTicket.setText(PropertiesController.getLangValue("ticket"));
        this.lblUnits.setText(PropertiesController.getLangValue("units"));
        this.lblUnitPrice.setText(PropertiesController.getLangValue("unitprice"));
        this.btnAddToTicket.setText(PropertiesController.getLangValue("addtoticket"));
        this.btnPrintTicket.setText(PropertiesController.getLangValue("printticket"));
        this.btnRemoveFromTicket.setText(PropertiesController.getLangValue("removefromticket"));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSaleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSaleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSaleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSaleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewSaleGUI dialog = new NewSaleGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne btnAddToTicket;
    private RSMaterialComponent.RSButtonIconOne btnClose;
    private RSMaterialComponent.RSButtonMaterialOne btnPrintTicket;
    private RSMaterialComponent.RSButtonMaterialOne btnRemoveFromTicket;
    private RSMaterialComponent.RSComboBoxMaterial cboxProducts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSLabelTextIcon lblAddProduct;
    private RSMaterialComponent.RSLabelTextIcon lblNewSale;
    private RSMaterialComponent.RSLabelTextIcon lblTicket;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JLabel lblUnits;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSTableMetroCustom tblTicket;
    private RSMaterialComponent.RSTextFieldMaterial txtUnitPrice;
    private RSMaterialComponent.RSTextFieldMaterial txtUnits;
    // End of variables declaration//GEN-END:variables
}
