/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentation;

import domain.Product;
import domain.Order;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import utilities.PropertiesController;
import utilities.Utilidades;

/**
 *
 * @author erome
 */
public class OrderCreatorGUI extends javax.swing.JDialog {

    private JFrame parent;
    /** Creates new form OrderCreatorGUI */
    public OrderCreatorGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = (JFrame)parent;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNewOrder = new RSMaterialComponent.RSLabelTextIcon();
        btnAllProducts = new RSMaterialComponent.RSButtonShapeIcon();
        btnSecurityProducts = new RSMaterialComponent.RSButtonShapeIcon();
        btnZeroProducts = new RSMaterialComponent.RSButtonShapeIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new RSMaterialComponent.RSTableMetroCustom();
        lblUnits = new javax.swing.JLabel();
        txtUnits = new RSMaterialComponent.RSTextFieldOne();
        btnDone = new RSMaterialComponent.RSButtonIconOne();
        btnCancel = new RSMaterialComponent.RSButtonIconOne();
        lblTotalOrderCost = new javax.swing.JLabel();
        txtTotalCost = new RSMaterialComponent.RSTextFieldOne();
        lblEuro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 51, 52));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 96, 0), 2));

        lblNewOrder.setForeground(new java.awt.Color(239, 96, 0));
        lblNewOrder.setText("New Order");
        lblNewOrder.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOPPING_CART);

        btnAllProducts.setBackground(new java.awt.Color(239, 96, 0));
        btnAllProducts.setToolTipText("All Products");
        btnAllProducts.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnAllProducts.setEnabled(false);
        btnAllProducts.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAllProducts.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ALL_INCLUSIVE);
        btnAllProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllProductsActionPerformed(evt);
            }
        });

        btnSecurityProducts.setBackground(new java.awt.Color(239, 96, 0));
        btnSecurityProducts.setToolTipText("Security Stock Products");
        btnSecurityProducts.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnSecurityProducts.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnSecurityProducts.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ANNOUNCEMENT);
        btnSecurityProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityProductsActionPerformed(evt);
            }
        });

        btnZeroProducts.setBackground(new java.awt.Color(239, 96, 0));
        btnZeroProducts.setToolTipText("Zero Stock Products");
        btnZeroProducts.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnZeroProducts.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnZeroProducts.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NOT_INTERESTED);
        btnZeroProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroProductsActionPerformed(evt);
            }
        });

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProducts.setBackgoundHead(new java.awt.Color(239, 96, 0));
        tblProducts.setBackgoundHover(new java.awt.Color(239, 96, 0));
        jScrollPane1.setViewportView(tblProducts);

        lblUnits.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUnits.setForeground(new java.awt.Color(255, 255, 255));
        lblUnits.setText("Units:");

        txtUnits.setForeground(new java.awt.Color(239, 96, 0));
        txtUnits.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnits.setText("0");
        txtUnits.setBorderColor(new java.awt.Color(239, 96, 0));
        txtUnits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnitsKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnitsKeyTyped(evt);
            }
        });

        btnDone.setBackground(new java.awt.Color(0, 204, 0));
        btnDone.setBackgroundHover(new java.awt.Color(0, 255, 0));
        btnDone.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DONE);
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 0, 0));
        btnCancel.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnCancel.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblTotalOrderCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalOrderCost.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalOrderCost.setText("Total Order Cost");

        txtTotalCost.setEditable(false);
        txtTotalCost.setForeground(new java.awt.Color(239, 96, 0));
        txtTotalCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalCost.setText("0");
        txtTotalCost.setBorderColor(new java.awt.Color(239, 96, 0));

        lblEuro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEuro.setForeground(new java.awt.Color(239, 96, 0));
        lblEuro.setText("€");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblUnits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalOrderCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEuro))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnSecurityProducts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(btnZeroProducts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnAllProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAllProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSecurityProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZeroProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnits)
                    .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalOrderCost)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEuro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAllProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllProductsActionPerformed
        btnAllProducts.setEnabled(false);
        btnZeroProducts.setEnabled(true);
        btnSecurityProducts.setEnabled(true);
        fillProductTable(createProductTableModel());
    }//GEN-LAST:event_btnAllProductsActionPerformed

    private void btnSecurityProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityProductsActionPerformed
        btnAllProducts.setEnabled(true);
        btnZeroProducts.setEnabled(true);
        btnSecurityProducts.setEnabled(false);
        fillProductTable(createProductTableModel());
    }//GEN-LAST:event_btnSecurityProductsActionPerformed

    private void btnZeroProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroProductsActionPerformed
        btnAllProducts.setEnabled(true);
        btnZeroProducts.setEnabled(false);
        btnSecurityProducts.setEnabled(true);
        fillProductTable(createProductTableModel());
    }//GEN-LAST:event_btnZeroProductsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnAllProducts.setEnabled(false);
        fillProductTable(createProductTableModel());
        setLanguageUI();
    }//GEN-LAST:event_formWindowOpened

    private void txtUnitsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnitsKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
           (c == KeyEvent.VK_BACK_SPACE) ||
           (c == KeyEvent.VK_DELETE))) {
          getToolkit().beep();
          evt.consume();
        }
    }//GEN-LAST:event_txtUnitsKeyTyped

    private void txtUnitsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnitsKeyReleased
        txtTotalCost.setText(Double.toString(Utilidades.round(Integer.parseInt(txtUnits.getText()) * (double)tblProducts.getValueAt(tblProducts.getSelectedRow(), 2),2)));
    }//GEN-LAST:event_txtUnitsKeyReleased

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        Order o = new Order((String)tblProducts.getValueAt(tblProducts.getSelectedRow(), 1), Integer.parseInt(txtUnits.getText()));
        o.getDao().createOrder(o);
    }//GEN-LAST:event_btnDoneActionPerformed

    private void setLanguageUI(){
        this.lblNewOrder.setText(PropertiesController.getLangValue("neworder"));
        this.lblUnits.setText(PropertiesController.getLangValue("units"));
        this.lblTotalOrderCost.setText(PropertiesController.getLangValue("totalordercost"));
    }
    
    private DefaultTableModel createProductTableModel(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn(PropertiesController.getLangValue("idproduct"));
        model.addColumn(PropertiesController.getLangValue("productname"));
        model.addColumn(PropertiesController.getLangValue("price"));
        model.addColumn(PropertiesController.getLangValue("stock"));
        model.addColumn(PropertiesController.getLangValue("securitystock"));
        model.addColumn(PropertiesController.getLangValue("minimumstock"));
        
        return model;
    }
    
    private void fillProductTable(DefaultTableModel model){
        Product p = new Product();
        LinkedList<Product> productsList = new LinkedList<>();
        if(!this.btnAllProducts.isEnabled())
            productsList = p.getDao().getProductsList();
        else if(!this.btnSecurityProducts.isEnabled())
            productsList = p.getDao().getSecurityStockProductsList();
        else if(!this.btnZeroProducts.isEnabled())
            productsList = p.getDao().getZeroProductsList();
        
        for(int i = 0; i < productsList.size(); i++){
            String deleted = PropertiesController.getLangValue("no");;
            if(productsList.get(i).isDeleted()){
                deleted = PropertiesController.getLangValue("yes");
            }
            Object[] row = new Object[]{
                productsList.get(i).getIdproduct(),
                productsList.get(i).getProductname(),
                productsList.get(i).getPrice(),
                productsList.get(i).getStock(),
                productsList.get(i).getSecuritystock(),
                productsList.get(i).getMinimumstock()
            };
            if(!productsList.get(i).isDeleted())
                model.addRow(row);
        }
        this.tblProducts.setModel(model);
        tblProducts.clearSelection();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OrderCreatorGUI dialog = new OrderCreatorGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShapeIcon btnAllProducts;
    private RSMaterialComponent.RSButtonIconOne btnCancel;
    private RSMaterialComponent.RSButtonIconOne btnDone;
    private RSMaterialComponent.RSButtonShapeIcon btnSecurityProducts;
    private RSMaterialComponent.RSButtonShapeIcon btnZeroProducts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEuro;
    private RSMaterialComponent.RSLabelTextIcon lblNewOrder;
    private javax.swing.JLabel lblTotalOrderCost;
    private javax.swing.JLabel lblUnits;
    private RSMaterialComponent.RSTableMetroCustom tblProducts;
    private RSMaterialComponent.RSTextFieldOne txtTotalCost;
    private RSMaterialComponent.RSTextFieldOne txtUnits;
    // End of variables declaration//GEN-END:variables

}
