/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Profile;
import domain.RegistredUser;
import rojeru_san.efectos.ValoresEnum.ICONS;
import utilities.PropertiesController;

/**
 *
 * @author erome
 */
public class ProfileEditorGUI extends javax.swing.JDialog {
    
    private int idUser;
    private Profile profile;
    
    public ProfileEditorGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLanguageUI();
    }
    
    public ProfileEditorGUI(java.awt.Frame parent, boolean modal, RegistredUser myUser) {
        this(parent, modal);
        this.idUser = myUser.getIdUser();
        Profile p = new Profile();
        this.profile = p.getDao().getProfileData(idUser);
        setProfileIntoFields();
    }
    
    public ProfileEditorGUI(java.awt.Frame parent, boolean modal, int idUser) {
        this(parent, modal);
        this.idUser = idUser;
        Profile p = new Profile();
        this.profile = p.getDao().getProfileData(idUser);
        setProfileIntoFields();
    }
    
    private void setProfileIntoFields(){
        Profile p = new Profile();
        this.profile = p.getDao().getProfileData(idUser);
        this.txtName.setText(profile.getName());
        this.txtSurname.setText(profile.getSurname());
        this.txtEmail.setText(profile.getEmail());
        this.txtTelegramUser.setText(profile.getTelegramUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        lblEditProfile = new RSMaterialComponent.RSLabelTextIcon();
        txtName = new RSMaterialComponent.RSTextFieldOne();
        txtSurname = new RSMaterialComponent.RSTextFieldOne();
        txtEmail = new RSMaterialComponent.RSTextFieldOne();
        txtTelegramUser = new RSMaterialComponent.RSTextFieldOne();
        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelegramUser = new javax.swing.JLabel();
        btnEditSave = new RSMaterialComponent.RSButtonIconTwo();
        btnCancelClose = new RSMaterialComponent.RSButtonIconOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(50, 51, 52));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 96, 0), 2));

        lblEditProfile.setForeground(new java.awt.Color(239, 96, 0));
        lblEditProfile.setText("Edit Profile");
        lblEditProfile.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);

        txtName.setEditable(false);
        txtName.setForeground(new java.awt.Color(239, 96, 0));
        txtName.setBorderColor(new java.awt.Color(239, 96, 0));
        txtName.setPhColor(new java.awt.Color(239, 96, 0));
        txtName.setPlaceholder("");

        txtSurname.setEditable(false);
        txtSurname.setForeground(new java.awt.Color(239, 96, 0));
        txtSurname.setBorderColor(new java.awt.Color(239, 96, 0));
        txtSurname.setPhColor(new java.awt.Color(239, 96, 0));
        txtSurname.setPlaceholder("");

        txtEmail.setEditable(false);
        txtEmail.setForeground(new java.awt.Color(239, 96, 0));
        txtEmail.setBorderColor(new java.awt.Color(239, 96, 0));
        txtEmail.setPhColor(new java.awt.Color(239, 96, 0));
        txtEmail.setPlaceholder("");

        txtTelegramUser.setEditable(false);
        txtTelegramUser.setForeground(new java.awt.Color(239, 96, 0));
        txtTelegramUser.setBorderColor(new java.awt.Color(239, 96, 0));
        txtTelegramUser.setPhColor(new java.awt.Color(239, 96, 0));
        txtTelegramUser.setPlaceholder("");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");

        lblSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSurname.setForeground(new java.awt.Color(255, 255, 255));
        lblSurname.setText("Surname");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");

        lblTelegramUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelegramUser.setForeground(new java.awt.Color(255, 255, 255));
        lblTelegramUser.setText("Telegram User");

        btnEditSave.setBackground(new java.awt.Color(239, 96, 0));
        btnEditSave.setBackgroundHover(new java.awt.Color(255, 137, 25));
        btnEditSave.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSaveActionPerformed(evt);
            }
        });

        btnCancelClose.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelClose.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnCancelClose.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnCancelClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelegramUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName)
                            .addComponent(lblSurname)
                            .addComponent(lblEmail)
                            .addComponent(lblTelegramUser)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnEditSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCancelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSurname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelegramUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelegramUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSaveActionPerformed
        if(btnEditSave.getIcons().equals(ICONS.EDIT)){ //Activar Edicion
            btnCancelClose.setIcons(ICONS.CANCEL); //Mientras edito puedo cancelar la edicion
            btnEditSave.setIcons(ICONS.SAVE); //Cambio el icono a guardar
            txtName.setEditable(true);
            txtSurname.setEditable(true);
            txtEmail.setEditable(true);
            txtTelegramUser.setEditable(true);
            
        }else if(btnEditSave.getIcons().equals(ICONS.SAVE)){ //Guardar cambios
            btnCancelClose.setIcons(ICONS.CLOSE); //Cuando guardo cambios puedo cerrar la edicion
            btnEditSave.setIcons(ICONS.EDIT); //Cambio el icono a edicion
            txtName.setEditable(false);
            txtSurname.setEditable(false);
            txtEmail.setEditable(false);
            txtTelegramUser.setEditable(false);
            
            //Modifico y guardo el perfil
            this.profile.setName(txtName.getText());
            this.profile.setSurname(txtSurname.getText());
            this.profile.setEmail(txtEmail.getText());
            this.profile.setTelegramUser(txtTelegramUser.getText());
            
            profile.getDao().setProfileData(profile, idUser);
            profile = profile.getDao().getProfileData(idUser);
            setProfileIntoFields();
        }
    }//GEN-LAST:event_btnEditSaveActionPerformed

    private void btnCancelCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelCloseActionPerformed
        if(btnCancelClose.getIcons().equals(ICONS.CLOSE)){
            this.dispose();
        }else if(btnCancelClose.getIcons().equals(ICONS.CANCEL)){
            btnCancelClose.setIcons(ICONS.CLOSE); //Cuando guardo cambios puedo cerrar la edicion
            btnEditSave.setIcons(ICONS.EDIT); //Cambio el icono a edicion
            txtName.setEditable(false);
            txtSurname.setEditable(false);
            txtEmail.setEditable(false);
            txtTelegramUser.setEditable(false);
            setProfileIntoFields();           
        }
    }//GEN-LAST:event_btnCancelCloseActionPerformed

    private void setLanguageUI(){
        this.lblEditProfile.setText(PropertiesController.getLangValue("editprofile"));
        this.lblName.setText(PropertiesController.getLangValue("name"));
        this.lblSurname.setText(PropertiesController.getLangValue("surname"));
        this.lblEmail.setText(PropertiesController.getLangValue("email"));
        this.lblTelegramUser.setText(PropertiesController.getLangValue("telegramuser"));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProfileEditorGUI dialog = new ProfileEditorGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private RSMaterialComponent.RSButtonIconOne btnCancelClose;
    private RSMaterialComponent.RSButtonIconTwo btnEditSave;
    private RSMaterialComponent.RSLabelTextIcon lblEditProfile;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTelegramUser;
    private RSMaterialComponent.RSTextFieldOne txtEmail;
    private RSMaterialComponent.RSTextFieldOne txtName;
    private RSMaterialComponent.RSTextFieldOne txtSurname;
    private RSMaterialComponent.RSTextFieldOne txtTelegramUser;
    // End of variables declaration//GEN-END:variables
}
